name: Upload Assets

on:
  pull_request: {}
  push:
    branches:
      - main

jobs:
  upload-assets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - run: yarn && yarn tsc

      - run: node lib/main.mjs
        name: run in Node tests

      - run: cp assets/index.html lib/
        name: Build web assets

      - name: Deploy to server
        id: deploy
        uses: Pendect/action-rsyncer@v2.0.0
        env:
          DEPLOY_KEY: ${{secrets.rsync_private_key}}
        with:
          flags: "-avzr --progress"
          options: ""
          ssh_options: ""
          src: "lib/*"
          dest: "rsync-user@tiye.me:/web-assets/repo/${{ github.repository }}"

      - name: Display status from deploy
        run: echo "${{ steps.deploy.outputs.status }}"
